name: .NET build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - '*'
  workflow_dispatch:

env:
  CONTINUOUS_INTEGRATION: true
  prodigo_portal_jwt_secret: "test-json-web-token-secret"
  prodigo_portal_db_connectionstring: "Server=localhost;Database=ProdigoPortal_test;User Id=SA; Password=ASDjk_shd$$jkASKJ19821;"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

  set-up-database:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build ]
    services:
      sql.data:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "ASDjk_shd$$jkASKJ19821"
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
    steps:
      - name: Update database
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef database update -p src/Infrastructure/Infrastructure.csproj
        env:
          ASPNETCORE_ENVIRONMENT: Development

  application-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build ]
    steps:
      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build tests/Application.Tests
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Application]*\"

  domain-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build ]
    steps:
      - name: Run tests and collect coverage
          dotnet test --no-build tests/Domain.Tests
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Domain]*\"

  client-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build ]
    steps:
      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build tests/Client.Tests
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Client]*\"

  infrastructure-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build, set-up-database ]
    steps:
      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build tests/Infrastructure.Tests
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Infrastructure]*\"

  server-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build, set-up-database ]
    steps:
      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build tests/Server.Tests
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Server]*\"

  server-integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ build, set-up-database ]
    steps:
      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build tests/Server.Tests.Integration
          -p:CollectCoverage=true
          -p:Threshold=80
          -p:ThresholdType=branch
          -p:CoverletOutput=../../CoverageResults/
          -p:ExcludeByFile=\"**/Program.cs\"
          -p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute\"
          -p:Include=\"[Server]*\"
